### ISSUE TITLE
1.3.10 does not work on Ruby 2.2.1 for Windows

### ISSUE THREAD

**Issue by kuroda** [sparklemotion/sqlite3-ruby#150]
As you may know, some people report issues on the ruby-forum: https://www.ruby-forum.com/topic/6874307.

In short, it emits the following error message:

```
LoadError: cannot load such file -- sqlite3/sqlite3_native
```

I think this is related to #137.

**Comment by jamesrf999** [comment]
2.2 support would be awesome. I tried to build it myself but quickly got into trouble with C++ build issues...

**Comment by kuroda** [comment]
@jamesrf999 Oh I see.

I am writing a book about Ruby on Rails for beginners. I have to specify which version of Ruby the readers should use.

Thanks for your information.

**Comment by topac** [comment]
+1

**Comment by kbhatt2006** [comment]
any update on this  !! I have ruby 2.2.2 - rails 4.2.1  on windows 8.1x64 and this problem persist. 

any workaround for now??  if not then do I have to scale back ruby version ? what version ?

**Comment by kuroda** [comment]
No update, unfortunately. You should use Ruby 2.1.x.

By the way, `bcrypt-ruby` has a similar [issue](https://github.com/codahale/bcrypt-ruby/issues/116) on Ruby 2.2.x, though I have not confirmed it by myself. If you develop a Rails application, it might be difficult to adopt Ruby 2.2.x for Windows platform even if our issue is solved.

I hope this situation will be improved before the advent of Rails 5.0, which is said to require Ruby 2.2.

**Comment by topac** [comment]
@kbhatt2006 The workaround for now: download the devkit from the rubyinstaller website, build the sqlite3 recipe here https://github.com/oneclick/knapsack-recipes and then build the gem with the command `gem install sqlite3 --platform=ruby`. This worked for me but it was a long journey : )

**Comment by jamesrf999** [comment]
Thanks for the tip!

**Comment by larskanis** [comment]
I've opened a pull request for adding ruby-2.2 support with a link to binary pre-release gems: https://github.com/sparklemotion/sqlite3-ruby/pull/159

**Comment by elizabrock** [comment]
For the other people experiencing this issue, the instructions on how to use @larskanis's version of the gem can be found in this comment: https://github.com/sparklemotion/nokogiri/issues/1256#issuecomment-121980221

**Comment by larskanis** [comment]
@tenderlove @luislavena Any chance to get a new release out, with updated binary Windows gems? PR #159 makes this easy and people are waiting since months. Do you need some help in maintaining this library?

**Comment by tomwebbi** [comment]
@ccoenen should i be using ruby 2.1.x???, i am having error installing sqlite3

**Comment by tomwebbi** [comment]
ruby 2.2.2 and rails 4.2.4, getting sqlite3 error:

Lenovo@Lenovo-PC /c/row/sqlite-autoconf-3081101
$ gem install sqlite3 --platform=ruby -- --with-sqlite3-include=/c:/row/sqlite-autoconf-3081101/sqlite3.h --with-sqlite3-lib=/c:/row/s
qlite-autoconf-3081101/.libs/sqlite3.o
Building native extensions with: '--with-sqlite3-include=c:/row/sqlite-autoconf-3081101/sqlite3.h --with-sqlite3-lib=c:/row/sqlite-auto
conf-3081101/.libs/sqlite3.o'
This could take a while...
ERROR:  Error installing sqlite3:
        ERROR: Failed to build gem native extension.

    c:/row/Ruby22/bin/ruby.exe -r ./siteconf20151003-5200-2aqp1n.rb extconf.rb --with-sqlite3-include=c:/row/sqlite-autoconf-3081101/sq
lite3.h --with-sqlite3-lib=c:/row/sqlite-autoconf-3081101/.libs/sqlite3.o
checking for sqlite3.h... no
sqlite3.h is missing. Install SQLite3 from http://www.sqlite.org/ first.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=c:/row/Ruby22/bin/$(RUBY_BASE_NAME)
        --with-sqlite3-dir
        --without-sqlite3-dir
        --with-sqlite3-include=${sqlite3-dir}/include
        --with-sqlite3-lib=${sqlite3-dir}/lib

extconf failed, exit code 1

Gem files will remain installed in c:/row/Ruby22/lib/ruby/gems/2.2.0/gems/sqlite3-1.3.10 for inspection.
Results logged to c:/row/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/sqlite3-1.3.10/gem_make.out

**Comment by ccoenen** [comment]
It is sad, but i think using ruby 2.1 is still the safer way right now on windows. This will become a problem once rails 5 is released. Rails 5 will require ruby 2.2 and at the current pace i do not think that all the broken gems will catch up.

**Comment by tomwebbi** [comment]
so whats the perfect version for begineer to download and start learning rails?

**Comment by ccoenen** [comment]
If you're trying to get into rails, you can get pretty far with the [railsinstaller](http://www.railsinstaller.org/en) - it's not the latest of everything, but that's not all that important when starting out. So the one that says "Ruby 2.1" will be fine for the most part. Please note that you will probably also need node.js, as some parts in Rails depend on a javascript environment on your computer. You can download that on the [node.js Website](https://nodejs.org/).

There's a really nice set of step-by-step [guides](http://guides.railsgirls.com/) that was created for the RailsGirls Events. It also [has details on common pitfalls in the windows setup](http://guides.railsgirls.com/install/#setup-for-windows) with railsinstaller that you _will_ run into after installing the RailsInstaller Ruby. It's not your fault, this comes up on every single machine.

Getting Rails to run is not the easiest thing in the world, i'm afraid. But usually this work upfront pays off. Most people like the language ruby and the framework ruby on rails a lot, once they run it successfully.

One more suggestion if I may: If you have a user group in your area, I'd also contact them. The ruby community is usually very welcoming. And meeting people in person is always nice! Have fun!

**Comment by luislavena** [comment]
@larskanis checking with @tenderlove if he can handle a release and if not, will look into your pull request and let you know.

**Comment by larskanis** [comment]
Alright, Luis!

**Comment by luislavena** [comment]
@larskanis checked with @tenderlove, I will get your work reviewed and merged and then plan for a release.

I'm a bit swamped with a deadline/release at work so will look at this over the weekend.

Thank you for your understanding.

**Comment by luislavena** [comment]
Hello all,

This has been sorted out and build has improved thanks to @larskanis contribution.

I've announced the release to sqlite3-ruby group:

https://groups.google.com/d/msg/sqlite3-ruby/YdvKkdVFa50/QWejGIPwBwAJ

As mentioned in the release notes, it includes binaries for 2.1.x and 2.2.x versions of Ruby on Windows.

Please feel free to cross-link that posting to ruby-talk since I'm no longer subscribed to it. Also post to any other mailing list you believe is worth mentioning.

@larskanis once again thank you for your contribution and improvements on building this and other gems.

Please note that this release only included patches to solve the issues related to Ruby 2.2 and Windows, no other patch has been merged or applied.

**off-topic: request and demands of support**

If you use and/or depend on sqlite3-ruby daily or for your work, please step up and offer yourself or possible your company to sponsor work on this project as maintainer. 

If you believe you're not qualified, think again, look at the commits and study them, will notice this *is not rocket science*, is just software.

Have a nice weekend.
