### ISSUE TITLE
Error message too general: "unable to open database file (SQLite3::CantOpenException)"

### ISSUE THREAD

**Issue by cosmocracy** [sparklemotion/sqlite3-ruby#176]
When attempting to open a file I receive the following error message:

```
unable to open database file (SQLite3::CantOpenException)
```

Since there are multiple possible avenues of troubleshooting, it would be helpful if the error message provided more insight into which aspect of opening the file failed, for example:
- Unable to open database file xyz.db - File not found
- Unable to open database file xyz.db - Read/write permission failure
- Unable to open database file xyz.db - File locked for read/write
- Unable to open database file xyz.db - File malformed
- Unable to open database file xyz.db - Required library "sqlite3.dll" missing
- ...etc...

**Comment by cosmocracy** [comment]
The last error message example--the shared library not being in my path--was the root cause but I wasted time exploring all of the other options since the given error wasn't precise enough.

**Comment by tenderlove** [comment]
Ok, since you were able to find the root cause of the problem, can you figure out how to get sqlite3 to report this issue?  Our error reporting comes from libsqlite itself, so either a) libsqlite doesn't have the information, or b) we're not extracting the information from libsqlite.  If it's b, then we can fix it, otherwise it will need to happen upstream.
