### ISSUE TITLE
Issue with 'sqlite3_adapter'

### ISSUE THREAD

**Issue by rlgreen91** [sparklemotion/sqlite3-ruby#191]
I am having trouble with an issue with 'sqlite3_adapter'.  I'm currently running Ruby 2.3 and Sqlite 1.3.11 on Windows 10 x64.  I have the railsinstaller environment basically replicated but with each component installed invidually (Ruby from RubyInstaller, Git, Bundler, etc.).  I have tried to run the server for both an older, Rails 4.1 application as well as a new Rails 5 application I created for testing.  Each time, I am stuck by the error: 
`Could not load 'active_record/connection_adapters/sqlite3_adapter'. Make sure that the adapter in config/database.yml is valid. If you use an adapter other than 'mysql2', 'postgresql' or 'sqlite3' add the necessary adapter gem to the Gemfile.`

My config/database.yml has the correct adapter.  I've checked, and I have the correct gem.  Sqlite itself is installed.  I'm not sure what the issue is here.  Is this something unique to Ruby 2.3 on Windows?  Will I need to do a fresh install? Do I need to downgrade to Ruby 2.2?  I'm just looking for more info before I spend another day on this.

**Comment by larskanis** [comment]
This is a duplication of #185 .

The sqlite3 binary gem doesn't support RubyInstaller-2.3 so far. It's probably best to stay at Ruby-2.2 on Windows, until #186 is merged and a new version is released.

**Comment by rlgreen91** [comment]
I would just like to point out that this isn't quite a duplication - while I did have the same environment as #185 , the error I'm getting is different.

**Comment by thisismydesign** [comment]
Try all answers here (or don't be on Windows because Ruby support sucks): https://stackoverflow.com/questions/17643897/cannot-load-such-file-sqlite3-sqlite3-native-loaderror-on-ruby-on-rails

**Comment by rlgreen91** [comment]
Unless something explicitly does not support a platform, saying to pick something else because support is lacking is, to be frank, a sucky response.  Regardless, this actually isn't a problem anymore for me given that I no longer use Railsinstaller.

Given that the corresponding fix has been merged, I would say this issue could be closed.  However, I will leave that up to the discretion of the maintainers.

**Comment by thisismydesign** [comment]
I would rather say the state of support is somewhat off topic here (partly because I don't enough details to draw conclusions of any projects in particular), hence I removed that part shortly after posting. Regardless if the latest major OS version and the most common practice to setup Ruby/Rails simply fails (on many levels not just here) then I'd say it's fair to point that out and maybe even to draw general conclusions.

**Comment by rlgreen91** [comment]
Except this is an issue from mid-2016, an older version of Ruby and the SQLite gem, and the proposed fix was merged in mid-2016.  Not to mention that this is no longer the most common practice to setup Ruby and Rails on Windows 10 - that's now through the Windows Subsystem for Linux.

You tried to be a smart-ass under the guise of providing a solution.  Next time, just provide the solution if it's even still needed.

**Comment by thisismydesign** [comment]
If you would've thought to actually look at the information I provided you would've seen that it's relevant in regards to platform, version and time frame. And that it's also an issue in 2018. How interesting is it that..

But I guess it's my mistake to not realize that an open widely generic `could not load` issue with no valuable information from 2 patches down the line with no PRs referenced is _exclusive to you_.

And instead of valuing the information or just simply acknowledging that it might be useful for others you decided to whine about something that's literally not even there. Wish you further good luck with open source.

**Comment by larskanis** [comment]
@rlgreen91 @thisismydesign Have you tried RubyInstaller-2.4+ especially the new version with built-in DevKit? For my taste it has gotten much better compared to the previous RubyInstaller versions.

The sqlite3 gem isn't well supported, so that it currently doesn't work with RubyInstaller-2.5 out of the box, but I posted a simple solution [here](https://stackoverflow.com/a/49736971/4743028).

**Comment by thisismydesign** [comment]
@larskanis From my (and many others') experience the issue can be resolved by going through the answers in the referenced StackOverflow thread. I don't plan to downgrade since I found a workaround with RubyInstaller-2.5 but thanks a lot for #229 it's good to see that there're plans to fix it.

**Comment by rlgreen91** [comment]
@larskanis thanks, but I'm no longer using RubyInstaller.

**Comment by flavorjones** [comment]
We're working on shipping precompiled native gems as well as increasing test coverage for people who want to use system libraries. If you're curious please follow #320.
