### ISSUE TITLE
Getting started using this repo with windows

### ISSUE THREAD

**Issue by schneems** [sparklemotion/sqlite3-ruby#193]
Trying to follow the README on a new windows 8.1 machine i'm getting this

```
C:\projects\sqlite3-ruby>ruby setup.rb config
---> lib
---> lib/sqlite3
---> lib/sqlite3/2.2
<--- lib/sqlite3/2.2
<--- lib/sqlite3
<--- lib
---> ext
---> ext/sqlite3
C:/RailsInstaller/Ruby2.2.0/bin/ruby C:/projects/sqlite3-ruby/ext/sqlite3/extcon
f.rb
checking for sqlite3.h... *** C:/projects/sqlite3-ruby/ext/sqlite3/extconf.rb fa
iled ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=C:/projects/sqlite3-ruby/ext/sqlite3
        --curdir
        --ruby=C:/RailsInstaller/Ruby2.2.0/bin/$(RUBY_BASE_NAME)
        --with-sqlite3-dir
        --without-sqlite3-dir
        --with-sqlite3-include
        --without-sqlite3-include=${sqlite3-dir}/include
        --with-sqlite3-lib
        --without-sqlite3-lib=${sqlite3-dir}/lib
C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler
 failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/mkmf.rb:587:in `try_cpp'

        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/mkmf.rb:1113:in `block i
n find_header'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/mkmf.rb:911:in `block in
 checking_for'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/mkmf.rb:351:in `block (2
 levels) in postpone'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/mkmf.rb:351:in `block in
 postpone'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/mkmf.rb:347:in `postpone
'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/mkmf.rb:910:in `checking
_for'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/mkmf.rb:1112:in `find_he
ader'
        from C:/projects/sqlite3-ruby/ext/sqlite3/extconf.rb:30:in `<main>'
'system C:/RailsInstaller/Ruby2.2.0/bin/ruby C:/projects/sqlite3-ruby/ext/sqlite
3/extconf.rb ' failed
Try 'ruby setup.rb --help' for detailed usage.

C:\projects\sqlite3-ruby>
```

I'm able to install native extensions otherwise, it looks like I've got a working install of Ruby and devkit, not sure why this error.

Any ideas? cc/ @luislavena

**Comment by luislavena** [comment]
Hello @schneems, sorry for the delayed response.

I believe the instructions for `setup.rb` are missing an important part: sqlite3 library and bindings needs to be already installed in order to be used.

This of course renders the entire section of the README useless, at least for Windows users, as the existing binaries for sqlite3 might not work (or might not be easy to get and set on your Ruby/DevKit installation).

I believe you can provide to `setup.rb config` some options indicating where sqlite3 lib and headers are, but that is a bit more complicated, so going to skip that for the sake of your (and my) mental health.

The best approach to actually build this gem locally is use `rake` and the `gem native` task.

This gem depends on [`rake-compiler`](https://github.com/rake-compiler/rake-compiler) and [`mini-portile`](https://github.com/flavorjones/mini_portile) in order to build a vendorized version of sqlite3, compile the extension against it and then produce a binary gem from the code.

You can find the steps of getting all set locally in the `appveyor.yml` file: https://github.com/sparklemotion/sqlite3-ruby/blob/master/appveyor.yml#L8-L16

What it does:

- Install `bundler` (`gem install bundler`)
- Bundle dependencies (`bundle install`)
- Build native extension (against vendored version of sqlite3 (`rake native gem`)

This will produce a native gem that works against the specific version of Ruby you used. Due some limitation of [rake-compiler](https://github.com/rake-compiler/rake-compiler) and Ruby on Windows, is not possible to produce gems that carry binary extensions for the different ABI versions of Ruby (ie. 1.9, 2.0, 2.1, 2.2 and 2.3).

For that purpose, other developers have created [rake-compiler-dock](https://github.com/rake-compiler/rake-compiler-dock), which provides Linux/OSX cross-compilation and **fat-binaries** (term coined by Aaron Patterson [here](https://tenderlovemaking.com/2009/05/07/fat-binary-gems-make-the-rockin-world-go-round.html)) which bundles extensions linked against different versions of Ruby runtime library.

This allows a single binary bundle the extension for the different versions and load it at runtime. A sample of code showing this is part of this project: 

https://github.com/sparklemotion/sqlite3-ruby/blob/master/lib/sqlite3.rb#L1-L7

---

Please let me know if the above helps sorting this out on your end and do not hesitate on ask further questions.

Cheers!

**Comment by schneems** [comment]
You are amazing, hope your travels went well. I'll dig in some more this week.

**Comment by schneems** [comment]
Took me a bit longer to resume work on this due to some feature work with rails and sprockets-rails.

When I run the command i'm getting the same error

```ruby
PS C:\projects\sqlite3-ruby> bundle exec rake native gem
cd tmp/i386-mingw32/sqlite3_native/2.2.4
C:/RailsInstaller/Ruby2.2.0/bin/ruby.exe -I. ../../../../ext/sqlite3/extconf.rb
checking for sqlite3.h... *** ../../../../ext/sqlite3/extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=../../../../ext/sqlite3
        --curdir
        --ruby=C:/RailsInstaller/Ruby2.2.0/bin/$(RUBY_BASE_NAME)
        --with-sqlite3-dir
        --without-sqlite3-dir
        --with-sqlite3-include
        --without-sqlite3-include=${sqlite3-dir}/include
        --with-sqlite3-lib
        --without-sqlite3-lib=${sqlite3-dir}/lib
C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file.
(RuntimeError)
You have to install development tools first.
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/mkmf.rb:587:in `try_cpp'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/mkmf.rb:1113:in `block in find_header'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/mkmf.rb:1112:in `find_header'
        from ../../../../ext/sqlite3/extconf.rb:30:in `<main>'
rake aborted!
Command failed with status (1): [C:/RailsInstaller/Ruby2.2.0/bin/ruby.exe -...]

Tasks: TOP => native => native:i386-mingw32 => native:sqlite3:i386-mingw32 => tmp/i386-mingw32/stage/lib/sqlite3/2.2/sql
ite3_native.so => copy:sqlite3_native:i386-mingw32:2.2.4 => tmp/i386-mingw32/sqlite3_native/2.2.4/sqlite3_native.so => t
mp/i386-mingw32/sqlite3_native/2.2.4/Makefile
(See full trace by running task with --trace)
PS C:\projects\sqlite3-ruby>
```

I'm pretty sure i've got the developer tools installed and i can successfully `$ gem install sqlite3` so i'm not sure what's going on.  One thing to note is that i'm not using visual studio IDE instead i've only installed the VC++ build tools. I don't know if this makes any difference or not.

**Comment by luislavena** [comment]
Hello @schneems 

I'm not too familiar with the tools bundled with RailsInstaller nowdays, so going to assume that it ships with RubyInstaller + DevKit and that has been setup.

The VC++ build tools should not interfere with RubyInstaller and DevKit, as they are not normally activated and RubyInstaller uses MinGW (GCC) instead.

> I'm pretty sure i've got the developer tools installed and i can successfully $ gem install sqlite3 so I'm not sure what's going on.

When you run `gem install sqlite3`, it will use the precompiled binary instead of compile from source.

An easy way to test for DevKit being setup will be install a gem that requires compilation, either by forcing it or that lacks binaries for Windows in rubygems.org

Take for example the [oj](https://rubygems.org/gems/oj/versions) gem, it has no `x86-mingw32` or similar listed as platform. You can try:

```
C:\>gem install oj --platform=ruby
```

During installation, you should see a legend output to the terminal that reads the following:

```
Temporarily enhancing PATH to include DevKit...
```

If that is not present, then it means that DevKit wasn't installed :cry: 

It is possible that RailsInstaller didn't set it up correctly, but I don't have a Windows machine to confirm that.

There is a way to test if DevKit was installed, and is by forcing it to be run doing `-rdevkit` when invoking `ruby` (which can also be used with `rake`.

This is covered in RubyInstaller [DevKit Wiki page](https://github.com/oneclick/rubyinstaller/wiki/Development-Kit#example-native-rubygem-installations-using-the-devkit)

---

So the first I would suggest is check that DevKit has been installed:

- Check if `gem install` command works.
- Check if `ruby -rdevkit -e "puts :ok"` works (it might)

The last option will be force DevKit to be loaded in the environment by calling `devkitvars.bat` when using *Command Prompt* (`cmd.exe`) or by loading `devkitvars.ps1` when using *PowerShell*.

---

OT to this, there was a plan to simplify the whole DevKit installation issues by simply having a gem that hooks up RubyGems loading process and also offers download/installation of DevKit in a better way.

The Proof of Concept for this was published under [devkit-gem](https://github.com/oneclick/devkit-gem) and there is a [conversation on google groups](https://groups.google.com/forum/#!topic/rubyinstaller/fZAmPSlz4zM/discussion) about it

The bad thing about it is that remained just a PoC and **I** run out of steam to pursue it further (and lot of other reasons, anyway).

---

Let me know if any of the above works for you and what other error you receive from those.

Regards and have a nice day.

**Comment by larskanis** [comment]
@schneems You should be able to build the fat binary gems per [rake-compiler-dock](https://github.com/rake-compiler/rake-compiler-dock) like so:
```
cd c:\Users\%USERNAME%
git clone https://github.com/sparklemotion/sqlite3-ruby
cd sqlite3-ruby
bundle
rake gem:windows
```
There are some dependencies on Windows (Docker-Toolbox with VirtualBox), but in the end there should be 3 fat binary gems for all current RubyInstaller versions in the `pkg` directory.
