### ISSUE TITLE
Parsing JSON columns 

### ISSUE THREAD

**Issue by erdemgezer** [sparklemotion/sqlite3-ruby#569]
I have table with a JSON column such as:
```
create table metrics
  id integer primary key,
  title character,
  data json default (json('{}'))
);
```      

I can successfuly insert a record such as:
```
  row = {  "title": "Hello World", "data": { "impressions": 123, "clicks": 5 } }
  db = SQLite3::Database.new("storage/development.sqlite3", results_as_hash: true)
  db.execute("insert into metrics(sku, data) values (?,?)", [m["sku"], row.to_json])
```

However, when I query the table, the JSON field returns as a string:
```
  db = SQLite3::Database.new("storage/development.sqlite3", results_as_hash: true)
  result = db.query("select title, sku from metrics limit 1;").first
  
  {"sku"=>"Hello World", "data"=>"{\"impressions\":123,\"clicks\":5}"}
  
```

In that case I need to manually parse that data column to be able to use as a Hash.
```
hash = JSON.parse(result["data"])
{"impressions": 123, "click": 5}
```

When I try the same thing in Ruby on Rails, ActiveRecord automatically parses that JSON column into a Hash.

Is there a way that the parsin can happen automatically when I query the table?

Thanks

**Comment by flavorjones** [comment]
Thanks for asking this question. This library is intended to be a minimal layer to retrieve bytes from the database, and it does not do any type conversion/coercion.

Previous versions (< 2.0) provided a minimal interface for type conversion, but it was removed since it's not hard to write a custom type translator using basic Ruby. For an example of how to do this, take a look at the [Changelog entry for 2.0](https://github.com/sparklemotion/sqlite3-ruby/blob/main/CHANGELOG.md#200--2024-04-17).

One approach you might consider along those lines is something like:

```ruby
class MyTranslator < DelegateClass(SQLite3::ResultSet)
  def data
    JSON.parse(self["data"])
  end
end

# ...

result = MyTranslator.new(db.execute("select * from metrics limit 1;").first)
pp result.data
# => {"title"=>"Hello World", "data"=>{"impressions"=>123, "clicks"=>5}}
```

I hope this helps?
