### ISSUE TITLE
Gem 1.6.9 claims to be compatible with 1.9.0 while using `prepend` from 2.5 in extconf.rb

### ISSUE THREAD

**Issue by hurricup** [sparklemotion/sqlite3-ruby#579]
This `prepend` execution is conditional, so may work in one environment and not in another.

- https://rubygems.org/gems/sqlite3/versions/1.6.9
- https://github.com/sparklemotion/sqlite3-ruby/blob/v1.6.9/ext/sqlite3/extconf.rb#L92

I understand that 2.4 and others are old, but some systems still using them and would be nice to have a compatible version of the gem.

**Comment by flavorjones** [comment]
Hi @hurricup, sorry you're dealing with this. Yes, the gemspec had an incorrectly-large range of supported ruby versions due to general lack of maintenance for many years.

I unfortunately cannot modify existing releases to fix the gemspec, but I think the gem v1.4.x should work on Ruby 2.4 and earlier? No promises, though. Please try pinning to that version and let me know if you have problems with it.

**Comment by hurricup** [comment]
yes, but you can release 1.6.10 with replacing `prepend` with `unshift` and that should do it. rubygems will use it by default and it would work

**Comment by flavorjones** [comment]
I'm not going to release a v1.6.10 because that won't solve your problem, rubygems and bundler will still load v1.6.9 if you're on an older version of ruby.

**Comment by hurricup** [comment]
I'm sorry, I probably miss something. Won't the gem with the same version constraints with the higher version be prefered?

**Comment by flavorjones** [comment]
Ah, sorry, I misunderstood what you were asking me to do, I thought you were asking me to cut a release v1.6.10 that declared specifically it does not support Ruby 2.4.

I now understand what you're asking.

I really do apologize that this has made your life a bit harder. The gemspec had not received much love and the testing matrix was not in good shape, which led to the breakage. I truly wish this had been caught sooner.

But at the same time, I would prefer not to spend time testing and cutting a release for a branch that's been out of support for a year so that it's easier to use with a version of Ruby that's been out of support for four and a half years. Resurrecting the testing pipeline for older versions of Ruby is not trivial (unstable CI is why we dropped many older rubies from the pipeline in the first place). And I realize it's uncouth to say in some circles, but I also want to encourage users to stay on supported versions of Ruby for performance and security reasons, so while I don't want to make anyone's life harder, I don't necessarily want to make it easier to follow an antipattern.

I'm sorry if you disagree with that decision, but I hope that you're able to understand why I'm choosing not to work on this and that we can disagree respectfully. Again, the the workaround is straightforward: pin to the version of sqlite3 that works for your version of Ruby.

**Comment by hurricup** [comment]
Thank you for your detailed answer, I really appreciate the time you spent to explain everything.

And REALLY sorry for nagging, but considering all you wrote above, feels fine to just change a method you call, run tests you have on 2.4 and just publish it, without restoring full pipeline. 

Nothing should break (I know that most problems start with such assumption :) ). But in case something will go wrong, you will be able just to delist this new version from rubygems and just forget about the issue :)

Again sorry, and thanks for discussing this :)
